openapi: 3.0.3

info:
  title: Health Check API
  description: API for service health status including readiness and liveness checks.
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://{host}:{port}
    variables:
      host:
        default: "localhost"
      port:
        default: "8090"

paths:
  /health/liveness:
    get:
      summary: Liveness check
      description: Returns OK if the service is alive and running.
      responses:
        '200':
          description: Service is alive
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: Service is not alive

  /health/readiness:
    get:
      summary: Readiness check
      description: Returns OK if the service is ready to accept traffic.
      responses:
        '200':
          description: Service is ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
        '503':
          description: Service is not ready

components:
  schemas:
    HealthStatus:
      type: object
      properties:
        status:
          type: string
          example: "OK"
        timestamp:
          type: string
          format: date-time
          example: "2025-06-03T14:25:00Z"