run:
  timeout: 5m
  allow-parallel-runners: true

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/asgardeo/thunder)
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow
  gocritic:
    disabled-checks:
      - exitAfterDefer
      - ifElseChain
      - elseif
    enabled-tags:
      - diagnostic
  goimports:
    local-prefixes: github.com/asgardeo/thunder
  misspell:
    locale: US
    ignore-words:
      - cancelled
  lll:
    line-length: 120
  revive:
    rules:
      - name: struct-tag
        arguments: [ "json,inline" ]
      - name: var-naming
      - name: redundant-import-alias
      - name: comment-spacings
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: package-comments

issues:
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: false

output:
  show-stats: true
