template: testify
template-data:
  unroll-variadic: true
packages:
  github.com/asgardeo/thunder/internal/system/database/client:
    config:
      all: true
      dir: tests/mocks/database/clientmock
      structname: '{{.InterfaceName}}Mock'
      pkgname: clientmock
      filename: "{{.InterfaceName}}_mock.go"

  github.com/asgardeo/thunder/internal/system/database/provider:
    config:
      all: true
      dir: tests/mocks/database/providermock
      structname: '{{.InterfaceName}}Mock'
      pkgname: providermock
      filename: "{{.InterfaceName}}_mock.go"
