server:
  hostname: "localhost"
  port: 8090

security:
  cert_file: "repository/resources/security/server.crt"
  key_file: "repository/resources/security/server.key"

database:
  identity:
    type: "sqlite"
    path: "repository/database/thunderdb.db"
  runtime:
    type: "sqlite"
    path: "repository/database/runtimedb.db"

user_store:
  default_user:
    username: "thor"
    password: "thor123"
