server:
  hostname: "localhost"
  port: 8090

gate_client:
  hostname: "localhost"
  port: 9090

security:
  cert_file: "repository/resources/security/server.cert"
  key_file: "repository/resources/security/server.key"

database:
  identity:
    type: "sqlite"
    path: "repository/database/thunderdb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"
  runtime:
    type: "sqlite"
    path: "repository/database/runtimedb.db"
    options: "_journal_mode=WAL&_busy_timeout=5000"

oauth:
  jwt:
    issuer: "thunder"
    validity_period: 3600

authenticator:
  default: "BasicAuthenticator"
  authenticators:
    - name: "BasicAuthenticator"
      type: "local"
      display_name: "Username & Password"
      description: "Login with username and password"

flow:
  graph_directory: "repository/resources/graphs/"
  authn:
    default_flow: "auth_flow_config_basic"

# provider:
#   sms:
#     default_provider: "twilio"
#     providers:
#       - name: "twilio"
#         provider: "twilio"
#         display_name: "Twilio SMS Provider"
#         description: "Send SMS using Twilio"
#         properties:
#           account_sid: ""
#           auth_token: ""
#           sender_id: ""
#       - name: "vonage"
#         provider: "vonage"
#         display_name: "Vonage SMS Provider"
#         description: "Send SMS using Vonage"
#         properties:
#           api_key: ""
#           api_secret: ""
#           sender_id: ""
#       - name: "custom"
#         provider: "custom"
#         display_name: "Custom SMS Provider"
#         description: "Send SMS using a custom provider"
#         properties:
#           url: ""
#           http_method: "POST"
#           http_headers: ""
#           content_type: "JSON"
#           payload_template: ""
