# This workflow will build the project on pull requests with tests
# Uses:
#   OS: ubuntu-latest
#   Go: go 1.x

name: PR Builder

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  GOFLAGS: "-mod=readonly"

jobs:
  build:
    if: ${{ github.event.label.name == 'trigger-pr-builder' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.x"

      - name: Cache Go modules
        uses: actions/cache@v4
        id: cache-go-modules
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-modules-

      - name: Install dependencies
        run: |
          cd backend
          go mod download
          cd ../tests/integration
          go mod download

      - name: Build and test
        run: |
          set -e
          make all
